[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

[template.environment]
  NEON_DATABASE_URL = "Postgres connection string from Neon"